import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Nav from "../components/nav"
import Benefits from "../components/benefits"
import FAQ from "../components/faq"
import Card from "../components/card"
import Hero from "../components/header"
import Footer from "../components/footer"
export default function Home() {
  return (
    <div >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Nav />
      <Hero />
      <Card />
      <Benefits />
      <FAQ />
      <Footer />
    </div >
  )
}
